config/routes.rb
Rails.application.routes.draw do

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base

validates :name, presence: { message: "required." }, length: { minimum: 3 }  
validates :email, presence: true,  format: /@/ 
validates :description, presence: { message: "required." }
                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
	@comments = Comment.all

	end

	def new
	@comment = Comment.new  

	end

	def create 
		@comment = Comment.new(comment_params) 
  		if @comment.save
  		redirect_to @comment
  		else
  		render "new"
  		end	
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy  

		redirect_to @comment
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update(comment_params)
		redirect_to @comment
		else
		render	"edit"
		end	
	end

	private


	def comment_params
		params.require(:comment).permit(:name, :email, :description)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h3>Edit</h3>


Edit comment

<%= form_for @comment , url: comment_path, method: :PATCH  do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
 <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :enviar%>
  </p>
<% end %>


<h3> <%= link_to "Cancelar", comments_path%>  </h3>

app/views/comments/index.html.erb
<h1>index</h1>

<%  @comments.each do |f|%>  
<ul>
<li> <strong> Number: <%=  f.id%> </strong> <small> Date: <%=  f.created_at%> </small></li>  	
<li> Name:<%=  f.name%>  </li>
<li> Email: <%=  f.email%>  </li>
<li> Description: <%=  f.description%>  </li>
</ul>


	<%= link_to 'Show', comment_path(f) %>
	<%= link_to 'Edit', edit_comment_path(f) %>
	<%= link_to 'Destroy', comment_path(f) , method: :delete, data: { confirm: 'Are you sure?' } %>

<%  end %>  


 <h3> <%=  link_to "Crear Comment", new_comment_path%>  </h3> 	

app/views/comments/new.html.erb
<h3>New </h3> 

<%= form_for @comment , url: comments_path do |f| %>
 
<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message  %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
 <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :enviar%>
  </p>
<% end %>


<h3> <%= link_to "Cancelar", comments_path%>  </h3>

app/views/comments/show.html.erb
<h3>Show</h3>
	
<h1>Comentario:</h1>
<h4> Nombre: <%= @comment.name %> </h4>
<h4> Email: <%= @comment.email%>  </h4>
<h4> Descripcion:<%= @comment.description %> </h4>



<h3> <%= link_to "Index", comments_path%>  </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>